branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - name: "@semantic-release/git"
    config:
      assets:
        - package.json
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"